export type TripDay = {
  id: number
  date: string
  weekday: string
  place: string
  title: string
  subtitle: string
  coordinates: [number, number]
  mapZoom: number
  transport: string[]
  stay?: string
  activities: string[]
  tags: string[]
  overnight?: boolean
}

export const tripDays: TripDay[] = [
  {
    id: 1,
    date: '09.25',
    weekday: '周五',
    place: '斯塔万格',
    title: '穿越欧洲，抵达峡湾之门',
    subtitle: '北京 · 维也纳 · 奥斯陆 · 斯塔万格',
    coordinates: [5.7331, 58.969],
    mapZoom: 8.4,
    transport: [
      'OS8004 · 02:50 北京首都 T3 → 06:50 维也纳 T3',
      'OS977 · 13:00 维也纳 T3 → 15:15 奥斯陆',
      'DY548 · 20:00 奥斯陆 → 20:50 斯塔万格',
    ],
    stay: 'Radisson Blu Atlantic Hotel Stavanger · 已预订',
    activities: ['抵达后视情况寄存大件行李', '在机场用晚餐，转机前往斯塔万格'],
    tags: ['飞行日', '转机'],
  },
  {
    id: 2,
    date: '09.26',
    weekday: '周六',
    place: '吕瑟峡湾',
    title: '登上布道石',
    subtitle: '悬于峡湾之上的经典徒步',
    coordinates: [6.1904, 58.9864],
    mapZoom: 10.8,
    transport: [
      '布道石往返大巴 · 待订',
      'SK4042 · 20:10 斯塔万格 → 21:05 奥斯陆 · 待订',
    ],
    stay: 'Radisson Blu Airport Hotel Oslo Gardermoen · 已预订',
    activities: ['布道石 Pulpit Rock 徒步', '傍晚返回斯塔万格机场', '夜宿奥斯陆机场附近'],
    tags: ['徒步', '峡湾'],
  },
  {
    id: 3,
    date: '09.27',
    weekday: '周日',
    place: 'Reine',
    title: '飞越峡湾，渡海进入罗弗敦',
    subtitle: '奥斯陆 · 博德 · Moskenes · Reine',
    coordinates: [13.096533, 67.941533],
    mapZoom: 10,
    transport: [
      'DY340 · 09:00 奥斯陆 → 10:30 博德',
      '出租车 · 博德机场 → 博德渡轮码头 · 约10分钟',
      'Torghatten Nord · 13:00 博德 → 16:15 Moskenes · 已预订',
    ],
    stay: 'Margithuset · Reine · 已预订至 9/29',
    activities: ['10:30 抵达博德后打车前往渡轮码头', '最晚12:15到达预订通道', '13:00乘渡轮横渡Vestfjorden', '16:15抵达Moskenes后前往Margithuset'],
    tags: ['北极圈', '飞行', '渡轮'],
  },
  {
    id: 4,
    date: '09.28',
    weekday: '周一',
    place: '西罗弗敦',
    title: '驶向群岛尽头',
    subtitle: 'Å · Sakrisøy · Reinebringen',
    coordinates: [13.096533, 67.941533],
    mapZoom: 10,
    transport: ['公交300/742或Reine Taxi · 南部短途往返'],
    stay: 'Margithuset · 已预订',
    activities: ['08:30–09:00 从Margithuset出发', 'Å渔村与Sakrisøy黄木屋', 'Anita’s Sjømat海鲜汉堡', 'Reinebringen阶梯徒步', '雨雪结冰则改去Ramberg白沙滩'],
    tags: ['公路', '摄影'],
  },
  {
    id: 5,
    date: '09.29',
    weekday: '周二',
    place: 'Reine → Svolvær',
    title: '沿E10穿越群岛',
    subtitle: '300路 · Svinøya · Henningsvær',
    coordinates: [14.57965, 68.23437],
    mapZoom: 10,
    transport: ['约11:45 公交300路 Reine → Svolvær；下午公交743路往返Henningsvær'],
    stay: 'Svinøya Rorbuer · 已预订',
    activities: ['11:00退房并前往公交站', '乘300路穿越E10，约14:30入住Svinøya', '下午乘743路游览Henningsvær', '渔村、岩石足球场与Festvågtind视角', '晚上返回酒店看极光'],
    tags: ['自由行', '极光'],
  },
  {
    id: 6,
    date: '09.30',
    weekday: '周三',
    place: '挪威海',
    title: '乘邮轮北上',
    subtitle: '斯沃尔维尔 → 特罗姆瑟',
    coordinates: [16.5415, 68.7988],
    mapZoom: 6.8,
    transport: ['沿海邮轮 · 22:30 斯沃尔维尔 → 次日 14:30 特罗姆瑟 · 已预订'],
    activities: ['早晨退房并寄存行李', 'Trollfjord 静音电动巡游或 RIB 海鹰 Safari 二选一', '巡游后市中心 City Walk 与购物', '返回取行李并提前到邮轮码头'],
    tags: ['邮轮', '过夜航行'],
    overnight: true,
  },
  {
    id: 7,
    date: '10.01',
    weekday: '周四',
    place: '特罗姆瑟',
    title: '走进北极之都',
    subtitle: '城市、雪山与第一场极光',
    coordinates: [18.9553, 69.6492],
    mapZoom: 10.5,
    transport: ['14:30 邮轮抵达特罗姆瑟'],
    stay: 'Skaret by VANDER · 2套公寓 · 已预订至 10/04',
    activities: ['入住并寄存行李', '北极大教堂', '缆车或 Sherpatrappa 半山观景台', '城市漫步', '夜间追极光'],
    tags: ['城市', '极光'],
  },
  {
    id: 8,
    date: '10.02',
    weekday: '周五',
    place: '特罗姆瑟',
    title: '在北境追逐自然',
    subtitle: '把选择交给当天的风与雪',
    coordinates: [18.9553, 69.6492],
    mapZoom: 9.2,
    transport: ['当地一日游 · 待选择'],
    stay: 'Skaret by VANDER · 已预订',
    activities: ['观鲸 / 海钓与峡湾邮轮 / Senja 一日游 / 狗拉雪橇', '夜间追极光'],
    tags: ['自然体验', '极光'],
  },
  {
    id: 9,
    date: '10.03',
    weekday: '周六',
    place: '特罗姆瑟',
    title: '北境的自由日',
    subtitle: '补上最想体验的那一项',
    coordinates: [18.9553, 69.6492],
    mapZoom: 9.2,
    transport: ['当地一日游 · 待选择'],
    stay: 'Skaret by VANDER · 已预订',
    activities: ['灵活安排观鲸、峡湾、Senja 或狗拉雪橇', '最后一晚追极光'],
    tags: ['机动日', '极光'],
  },
  {
    id: 10,
    date: '10.04',
    weekday: '周日',
    place: '奥斯陆',
    title: '回到城市',
    subtitle: '特罗姆瑟 → 奥斯陆',
    coordinates: [10.7522, 59.9139],
    mapZoom: 10.4,
    transport: ['DY381 · 12:55 特罗姆瑟 → 14:50 奥斯陆 · 待订'],
    stay: 'Comfort Hotel Grand Central · 早餐含 · 已预订',
    activities: ['攀岩馆', '购物', '视情况游览室内景点'],
    tags: ['城市', '购物'],
  },
  {
    id: 11,
    date: '10.05',
    weekday: '周一',
    place: '返程',
    title: '带着北境回家',
    subtitle: '奥斯陆 · 慕尼黑 · 北京',
    coordinates: [10.7522, 59.9139],
    mapZoom: 8.5,
    transport: [
      'LH2453 · 11:45 奥斯陆 → 14:00 慕尼黑 T2',
      'LH722 · 19:40 慕尼黑 T2 → 次日 11:45 北京首都 T3',
    ],
    activities: ['早餐后整理行李', '提前前往奥斯陆机场'],
    tags: ['返程', '转机'],
  },
]

